// <auto-generated />
namespace Online_Secondhand_Store.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class dataBase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dataBase));
        
        string IMigrationMetadata.Id
        {
            get { return "202409270954142_dataBase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
